### PR TITLE
Avoid some false positives when prefixing root-relative paths with CDN

### LINKED ISSUE #13: cdnPrefixForRootPaths incorrectly prefixes non-root paths
Suppose we have this file tree:
```
static
├── img
│   └── background.png
└── stylesheets
    └── main.css
```

And the contents of `main.css` are:
```
/* main.css */
body {
  background: url("../img/background.png");
}
```

Also suppose theis configuration:
```
assetFingerprint: {
  "options": {
    "findAndReplaceFiles": [
      "dist/**/*.css"
    ],
    "cdnPrefixForRootPaths": "https://cdn.domain.com"
  },
  "dist": {
    "files": [
      {
        "expand": true,
        "cwd": "static",
        "src": [
          "img/**/*",
          "css/main.css"
        ],
        "dest": "dist"
      }
    ]
  }
}
```

Then we would end up with something like:
```
dist
├── img
│   └── background-d29d63efad87cf6df07cb6e696bb219c.png
└── stylesheets
    └── main-bfd72b16d8cedfcecccced5c5b16d51c.css

/* main.css */
body {
  background: url("..https://cdn.domain.com/img/background-d29d63efad87cf6df07cb6e696bb219c.png");
}
```

Notice that the URL for the image ends up being completely mangled as `"..https://cdn.domain.com/img/background-d29d63efad87cf6df07cb6e696bb219c.png"`.

This one is difficult to solve completely since it's hard to really know what is a root-relative path without having an actual language parser. I think one stop-gap would be to make the regex a bit more specific, checking for common boundary characters.

### PR DESCRIPTION
**Pull request by sudowork**
In a case like `../originalName.png`, you would end up with
`..https://cdn.domain.com/hashedName.png`. In this scenario, you would
actually want to keep the relative path still `../hashedName.png`, but
with the fingerprinted filename.

Although we don't have a language parser to ensure we are looking at a
root-relative name, we can at least take try to be a bit more cautious
and look out for common boundaries.

Fixes #13

### CODE REVIEW

**Comment by sudowork** [comment]
I think this is probably not ready to merge. I would want to write some test cases. But I wanted to get your thoughts @searls on if this makes sense.

Examples of things that would pass this new regex:
```css
/* CSS usage */
url(/foo.png);
url("/foo.png");
url('/foo.png');
url( /foo.png );
```
```jade
<!-- HTML attributes and jade attributes -->
<link rel="stylesheet" href="/main.css">
<img src="/foo.png" />
<script src="/app.js">
img(src = /foo.png)
img(src=/foo.png)
```

**Comment by sudowork** [comment]
@searls I added in some tests, so I think it's probably ready.

**Comment by sudowork** [comment]
Another case where the previous regex would fail is if there was an absolute reference (e.g. `https://my.domain.com/someasset.png` would get mangled into `https://my.domain.comhttps://cdn.domain.com/someasset.png`). This PR should also resolve that.

**Comment by searls** [comment]
Seems legit  -- Thanks!

**Comment by searls** [comment]
Landed in 0.3.0 -- if you want to help more, a change you made caused an issue in which after running the test, `spec/fixtures/some-css.css` is changed and not reverted, causing git churn. I just `git checkout spec/fixtures/some-css.css`'d it for now since I don't use this module much, but next time someone tries to change it, it'll definitely be confusing (and they may accidentally commit the change, breaking the test)

**Pull request merged**
